language: python

branches:
  only:
  - master

python:
  - "2.7"
  - "3.6"
cache: pip

services:
  - postgresql

before_install:
  - sudo apt-get update

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database projetofinal_dev;' -U postgres
  

